### ISSUE TITLE
Create a new StackView based similar to the CardView component in Hypothesize

### ISSUE THREAD

**Issue by agyemanjp** [Hypothesize/somatic.js#15]
- Name it StackView
 - Add features/properties: Orientation, Alignment, Selection mode (e.g.,Multiple selection), Template property (component to convert the data value into an element), Selected style property
 - Rename _cardsList_ property to _items_; it should just be a simple array (or iterable) of values
 - Rename _customTheme_ to _appearance_

**Comment by diegocl02** [comment]
Already created
